// Before running this script, please read the Bitcoin documentation and all comments carefully!!

// Wallet Compatibility Verification Script
// ⚠️  SECURITY WARNING:
//   - This script logs partial addresses and key info for verification
//   - Only run in secure, private environments
//   - NEVER run with production keys in shared/public environments
//   - NEVER commit console output to git
//   - Use TESTNET keys for testing this script
// Why this matters:
// - Different wallets use different derivation paths
// - Electrum has quirks in how it exports master keys
// - Mismatched addresses = donations sent to addresses you can't see in your wallet
// Usage:
//   1. Get first 3 addresses from your wallet (see instructions below)
//   2. Update WALLET_ADDRESSES array below
//   3. Set BITCOIN_MASTER_VPRV (test) or BITCOIN_MASTER_ZPRV (prod) env var
//   4. Run: npx tsx verify-wallet-compatibility.ts
// How to get addresses from your wallet:
// ELECTRUM:
//   1. Open wallet in correct mode (testnet/mainnet)
//   2. View → Show Addresses
//   3. Copy first 3 "Receiving" addresses
// BITCOIN CORE:
//   Run: bitcoin-cli listreceivedbyaddress 0 true
//   Copy first 3 addresses
// TESTNET vs MAINNET:
//   - Testnet addresses start with: tb1q...
//   - Mainnet addresses start with: bc1q...

import { env } from '@/env.ts'
import { deriveBip84Address } from './src/libs/bitcoin/bip84.ts'

// ============================================================================
// CONFIGURATION: Update these with YOUR wallet's first 3 addresses
// ============================================================================

const WALLET_ADDRESSES = [
	'', // Address #0 from your wallet
	'', // Address #1 from your wallet
	'', // Address #2 from your wallet
]

// ============================================================================
// Verification Logic (no changes needed below)
// ============================================================================

const MASTER_KEY = env.BITCOIN_MASTER_ZPRV || env.BITCOIN_MASTER_VPRV

if (!MASTER_KEY) {
	console.error('❌ Error: Master key not found')
	console.error('')
	console.error('Set one of these environment variables:')
	console.error('  - BITCOIN_MASTER_VPRV (for testnet)')
	console.error('  - BITCOIN_MASTER_ZPRV (for mainnet)')
	console.error('')
	console.error('Example:')
	console.error(
		'  BITCOIN_MASTER_VPRV=vprv9s... npx tsx verify-wallet-compatibility.ts'
	)
	process.exit(1)
}

// Detect network from key prefix
const network = MASTER_KEY.startsWith('zprv') ? 'mainnet' : 'testnet'
const expectedPrefix = network === 'mainnet' ? 'bc1q' : 'tb1q'

// Check if user updated the placeholder addresses
if (WALLET_ADDRESSES[0]?.startsWith('REPLACE_WITH')) {
	console.error('❌ Error: You need to update WALLET_ADDRESSES')
	console.error('')
	console.error('Steps:')
	console.error('1. Open this file: verify-wallet-compatibility.ts')
	console.error('2. Find the WALLET_ADDRESSES array (line ~35)')
	console.error(
		'3. Replace REPLACE_WITH_ADDRESS_X with your actual wallet addresses'
	)
	console.error('')
	console.error('Your addresses should start with:', expectedPrefix)
	console.error('')
	console.error('See file header for instructions on getting addresses.')
	process.exit(1)
}

// Redact Bitcoin address for secure logging
function redactAddress(addr: string): string {
	if (!addr || addr.length < 20) return addr
	return `${addr.substring(0, 10)}...${addr.substring(addr.length - 6)}`
}

console.log('='.repeat(70))
console.log('WALLET COMPATIBILITY VERIFICATION')
console.log('='.repeat(70))
console.log('')
console.log(`Network: ${network}`)
console.log(
	`Master Key: ${MASTER_KEY.substring(0, 4)}... (${MASTER_KEY.length} chars)`
)
console.log('')
console.log('⚠️  Addresses shown in redacted form for security')
console.log('   Full addresses are compared internally')
console.log('')
console.log('Checking first 3 addresses...')
console.log('')

let allMatch = true

for (let i = 0; i < 3; i++) {
	const generated = deriveBip84Address(MASTER_KEY, i, network)
	const expected = WALLET_ADDRESSES[i]

	if (!expected) {
		console.error(`Missing wallet address at index ${i}`)
		allMatch = false
		continue
	}

	const match = generated === expected

	console.log(`Index ${i}:`)
	console.log(`  Wallet:    ${redactAddress(expected)}`)
	console.log(`  Generated: ${redactAddress(generated)}`)
	console.log(`  Match:     ${match ? '✅ YES' : '❌ NO'}`)
	if (!match) {
		console.log(
			`  ⚠️  Full comparison: wallet="${expected}" vs generated="${generated}"`
		)
	}
	console.log('')

	if (!match) {
		allMatch = false
	}
}

console.log('='.repeat(70))

if (allMatch) {
	console.log('✅ SUCCESS! Your wallet is compatible!')
	console.log('')
	console.log('What this means:')
	console.log('  - Addresses generated by our code match your wallet')
	console.log('  - Donations will appear in your wallet automatically')
	console.log('  - You can safely accept Bitcoin payments')
	console.log('')
	console.log('Next steps:')
	console.log('  1. Set BITCOIN_MASTER_VPRV/ZPRV in Convex')
	console.log('  2. Set BITCOIN_NETWORK in Convex')
	console.log('  3. Test with small amount first')
	console.log('')
} else {
	console.log('❌ FAILED! Addresses do not match!')
	console.log('')
	console.log('This means your wallet uses a different derivation path.')
	console.log('')
	console.log('Possible causes:')
	console.log('  1. Wrong wallet type (needs BIP84 native SegWit)')
	console.log('  2. Wrong network (testnet vs mainnet mismatch)')
	console.log('  3. Wallet uses non-standard derivation')
	console.log('  4. Wrong master key exported')
	console.log('')
	console.log('Solutions:')
	console.log('  1. Use Electrum wallet (recommended, tested)')
	console.log('  2. Export correct key from your wallet')
	console.log('  3. Update src/libs/bitcoin/bip84.ts to match your wallet')
	console.log('')
	console.log('⚠️  DO NOT accept real donations until this is fixed!')
	console.log('')
	process.exit(1)
}

console.log('='.repeat(70))
